import type { Metadata } from "next";
import { sarabun } from "./fonts";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sarabun.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}