import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'

const mitr = Mitr({
  variable: "--font-mitr",
  subsets: ["latin", "thai"],
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mitr.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}